import { ArrowRight, BookOpen, Download, PlayCircle, Search, Star } from 'lucide-react'

const courses = [
  ['Applied Panel Data for African Research','Prof. K. Moyo','12 lessons · Certificate','blue','Econometrics'],
  ['Banking Stress Tests & Financial Stability','Dr. David Okafor','8 lessons · Case-based','teal','Banking'],
  ['African Trade, AfCFTA & Industrial Policy','Prof. Amina Diallo','10 lessons · New','gold','Public policy'],
  ['Python for Economists','EconLab Faculty','16 lessons · Downloadable','green','Data science'],
]
export function Learning(){return <div className="page-wrap"><div className="page-hero"><p className="eyebrow">LEARNING & PUBLISHING</p><h1>Trusted economic knowledge, taught by verified experts.</h1><p>Courses, masterclasses, books, policy explainers, datasets and research pathways designed for economists working with African questions.</p></div><div className="library-banner"><div className="searchbox static inverse"><Search size={18}/><input placeholder="Search courses, books, datasets and policy explainers…"/></div><div className="browse-pills">{['Econometrics','Development','Banking','Public policy','Data science','Career skills'].map(x=><button key={x}>{x}</button>)}</div></div><div className="course-grid">{courses.map(([title,author,meta,color,cat])=><article className="course-card card" key={title}><div className={`course-cover cover-${color}`}><p>{cat}</p><PlayCircle size={36}/></div><div className="course-body"><p className="eyebrow">VERIFIED COURSE</p><h3>{title}</h3><p>{author}</p><div className="course-meta"><span><BookOpen size={15}/>{meta}</span><span><Star size={14} fill="currentColor"/>4.9</span></div><button className="secondary-btn full">View course <ArrowRight size={16}/></button></div></article>)}</div><section className="download-band card"><div className="download-icon"><Download size={26}/></div><div><p className="eyebrow">LOW-BANDWIDTH ACCESS</p><h2>Learning that works beyond perfect internet.</h2><p>Authorised courses can support downloadable notes, compressed video, captions, datasets and offline reading packs.</p></div><button className="secondary-btn">Explore downloads</button></section></div>}
