import { useState } from 'react'
import { ArrowRight, CheckCircle2, Clock3, FileSpreadsheet, FolderLock, Plus, Search, UserPlus, Users } from 'lucide-react'
import { researchRooms } from '../data/mock'

export function Research() {
  const [joined,setJoined] = useState<string[]>(['FIHW'])
  return <div className="page-wrap">
    <div className="page-hero split-hero research-hero"><div><p className="eyebrow">RESEARCH COMMUNITY</p><h1>Turn professional connections into serious research collaboration.</h1><p>Join topic groups, find co-authors, recruit research assistants, share datasets and preserve the contribution history behind every project.</p></div><button className="primary-btn"><Plus size={17}/> Start research group</button></div>
    <div className="research-feature-strip card"><div><Users size={19}/><span><strong>Open research groups</strong><small>Join projects that match your interests</small></span></div><div><UserPlus size={19}/><span><strong>Find collaborators</strong><small>Professors, analysts and students</small></span></div><div><FolderLock size={19}/><span><strong>Private workspaces</strong><small>Permissions, files and contribution records</small></span></div></div>
    <div className="search-filter-bar"><div className="searchbox static"><Search size={18}/><input placeholder="Search research groups, questions or fields…"/></div><button className="filter-chip active">Recommended</button><button className="filter-chip">Recruiting</button><button className="filter-chip">My groups</button></div>
    <div className="research-grid">
      {researchRooms.map(room => <article className="research-card card pro-research-card" key={room.code}><div className="research-top"><div className="project-code">{room.code}</div><span className={`status-chip ${room.status === 'Recruiting' ? 'recruiting' : ''}`}>{room.status}</span></div><p className="eyebrow">{room.field}</p><h3>{room.title}</h3><div className="country-list">{room.countries.map(c => <span key={c}>{c}</span>)}</div><div className="progress-label"><span>Project progress</span><strong>{room.progress}%</strong></div><div className="progress"><i style={{width:`${room.progress}%`}}/></div><div className="research-metrics"><span><Users size={16}/>{room.members} contributors</span><span><CheckCircle2 size={16}/>{room.tasks} tasks</span></div><button className={joined.includes(room.code)?'secondary-btn full':'primary-btn full'} onClick={()=>setJoined(v=>v.includes(room.code)?v.filter(x=>x!==room.code):[...v,room.code])}>{joined.includes(room.code)?'Open research group':'Join research group'} <ArrowRight size={16}/></button></article>)}
    </div>
    <section className="workspace-preview card"><div className="workspace-sidebar"><p className="eyebrow light">ACTIVE GROUP</p><h3>Food Inflation & Household Welfare</h3>{['Group feed','Tasks','Data room','Analysis log','Manuscript','Meetings','Contributors','Ethics & permissions'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div><div className="workspace-main"><div className="section-head"><div><p className="eyebrow">COLLABORATIVE WORKSPACE</p><h2>Shared research files</h2></div><button className="secondary-btn"><Plus size={15}/> Add file</button></div>{[['household_panel_v3.csv','Restricted'],['food_price_index.xlsx','Team access'],['cleaning_log.md','Team access'],['variable_dictionary.pdf','Read only']].map(([file,access])=><div className="file-row" key={file}><span className="file-icon"><FileSpreadsheet size={19}/></span><div><strong>{file}</strong><span>Version history available</span></div><em>{access}</em></div>)}</div><aside className="workspace-side"><div className="secure-badge"><FolderLock size={18}/>Role-based access</div><h4>Next group session</h4><p>Methods review and robustness-check planning.</p><div className="deadline"><Clock3 size={16}/> Thursday · 18:00 WAT</div></aside></section>
  </div>
}
