import { ArrowRight, CheckCircle2, Clock3, FileSpreadsheet, FolderLock, Plus, Search, Users } from 'lucide-react'
import { researchRooms } from '../data/mock'

export function Research() {
  return <div className="page-wrap">
    <div className="page-hero split-hero"><div><p className="eyebrow">RESEARCH COLLABORATION</p><h1>Research rooms built for serious economic work.</h1><p>Create cross-border teams, manage datasets, assign roles, document analytical decisions and keep authorship contributions visible from idea to publication.</p></div><button className="primary-btn"><Plus size={17}/> Create research room</button></div>
    <div className="search-filter-bar"><div className="searchbox static"><Search size={18}/><input placeholder="Search research rooms, topics or JEL fields…"/></div><button className="filter-chip active">My rooms</button><button className="filter-chip">Recruiting</button><button className="filter-chip">Public</button></div>
    <div className="research-grid">
      {researchRooms.map(room => <article className="research-card card" key={room.code}><div className="research-top"><div className="project-code">{room.code}</div><span className={`status-chip ${room.status === 'Recruiting' ? 'recruiting' : ''}`}>{room.status}</span></div><p className="eyebrow">{room.field}</p><h3>{room.title}</h3><div className="country-list">{room.countries.map(c => <span key={c}>{c}</span>)}</div><div className="progress-label"><span>Project progress</span><strong>{room.progress}%</strong></div><div className="progress"><i style={{width:`${room.progress}%`}}/></div><div className="research-metrics"><span><Users size={16}/>{room.members} contributors</span><span><CheckCircle2 size={16}/>{room.tasks} tasks</span></div><button className="secondary-btn full">Open research room <ArrowRight size={16}/></button></article>)}
    </div>
    <section className="workspace-preview card"><div className="workspace-sidebar"><p className="eyebrow light">PROJECT</p><h3>Food Inflation & Household Welfare</h3>{['Overview','Tasks','Data room','Analysis log','Manuscript','Meetings','Contributors','Ethics & permissions'].map((x,i)=><button className={i===2?'active':''} key={x}>{x}</button>)}</div><div className="workspace-main"><div className="section-head"><div><p className="eyebrow">SECURE DATA ROOM</p><h2>Project files</h2></div><button className="secondary-btn"><Plus size={15}/> Add file</button></div>{[['household_panel_v3.csv','Restricted'],['food_price_index.xlsx','Team access'],['cleaning_log.md','Team access'],['variable_dictionary.pdf','Read only']].map(([file,access])=><div className="file-row" key={file}><span className="file-icon"><FileSpreadsheet size={19}/></span><div><strong>{file}</strong><span>Version history available</span></div><em>{access}</em></div>)}</div><aside className="workspace-side"><div className="secure-badge"><FolderLock size={18}/>Role-based access</div><h4>Next milestone</h4><p>Complete robustness checks and prepare the methods memo.</p><div className="deadline"><Clock3 size={16}/> Due 18 September</div></aside></section>
  </div>
}
